name: rasterio-plotting
channels:
  - conda-forge
dependencies:
  - jupyter=1.0.*
  - matplotlib=3.1.*
  - numpy=1.17.*
  - pip=19.2.*
  - python=3.7.*
  - requests=2.22.*
  - scikit-image=0.15.*
  - pip:
    - rasterio==1.0.*

